### ISSUE TITLE
The galaxy brain badge

### ISSUE THREAD

**Issue by Iweisc** [drknzz/GitHub-Achievements#375]

**Comment by Iweisc** [comment]
It is the solution

**Comment by jvcByte** [comment]
this is not supposed to be difficult

**Comment by pavanran** [comment]
i think they closed it

**Comment by rubydamodar** [comment]
> i think they closed it

no u cant achieve brain galaxy badge easily

**Comment by Iweisc** [comment]
> > i think they closed it
> 
> no u cant achieve brain galaxy badge easily

Yes u can
