### ISSUE TITLE
How to get Open Sourcerer?

### ISSUE THREAD

**Issue by TTiannaiTT** [drknzz/GitHub-Achievements#395]
<img width="640" alt="{B6585992-D911-412E-A298-0D1391876DB8}" src="https://github.com/user-attachments/assets/2b80778b-b6ac-4a03-bc37-0f57cbf9839a">  

I wanna how to get this?  
Thanks!

**Comment by pietrohoff** [comment]
@TTiannaiTT The Open Sourcerer badge is not yet available on GitHub. Although it's mentioned as a future badge to recognize contributions to open source projects, it hasn't been officially released for users. Therefore, it’s currently not possible to earn it, but it’s expected to be launched in a future platform update.

**Comment by TTiannaiTT** [comment]
Got it, thank you very much!
