### ISSUE TITLE
All images are subject to link rot

### ISSUE THREAD

**Issue by seanpm2001** [drknzz/GitHub-Achievements#93]
Is it possible to add a `/media/` folder, and link to the images from here? It is not the best idea to base most of a repository off of a resource that can go down at any time for any reason. I don't think it would increase the repository size by very much either, especially if the images are in SVG format. I have seen many prominent images from `camo.githubusercontent.com` suddenly stop working, even from Microsoft-owned repositories themselves!

**Comment by drknzz** [comment]
Good idea, I'd accept a PR from someone who wants to do it.

**Comment by seanpm2001** [comment]
I have opened a pull request to fix this issue: https://github.com/drknzz/GitHub-Achievements/pull/103
